language: node_js

sudo: required

node_js:
  - "10.16.3"

env:
  - CXX=g++-7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-7

before_install:
  - export CXX="g++-7"
  - npm install -g npm@latest
  - npm install -g ganache-cli truffle

install:
  - npm install 

script:
  - ganache-cli -l 100000000 -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" > /dev/null &
  - truffle test