name: Repo Sync

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "git@github.com:synergatika/loyalty-contracts.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "ssh://git@ledger-git.dyne.org:2240/Synergy/loyalty-contracts.git"
        DESTINATION_BRANCH: "master"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH